spring.application.name=appoinment-service
server.port=8083
spring.datasource.url=jdbc:mysql://localhost:3306/appointmentdb
spring.datasource.username=root
spring.datasource.password=reshu@403216
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true